### ISSUE TITLE
Crear Actividad

### ISSUE THREAD

**Issue by Izydemon** [AlexanderAlvarezMarques/ULPGC-P4#12]
No redirecciona al perfil de la empresa una vez creada una actividad

**Comment by Izydemon** [comment]
Poder subir imagen al crear actividad

**Comment by AlexanderAlvarezMarques** [comment]
Ya se guarda en la base de datos y redirije al index

**Comment by AlexanderAlvarezMarques** [comment]
Añadido sistema para subir imagen. Esta comentado debido a que luego produce un error al intentar mostrar la imagen.

**Comment by Izydemon** [comment]
Da error con la variable $fail
Syntax Error: unexpectedT_VARIABLE
